namespace DnD.Enums
{
    public enum ClassType
    {
        Artificer = 0,
        Barbarian = 1,
        Bard = 2,
        Cleric = 3,
        Druid = 4,
        Fighter = 5,
        Monk = 6,
        Paladin = 7,
        Ranger = 8,
        Rogue = 9,
        Sorcerer = 10,
        Warlock = 11,
        Wizard = 12,
    }

    public enum ClassSubType
    {
        // Artificer
        Alchemist,
        Armorer,
        Artillerist,
        BattleSmith,
        // Barbarian
        PathOfTheAncestralGuardian,
        PathOfTheBattlerager,
        PathOfTheBeast,
        PathOfTheBerserker,
        PathOfTheStormHerald,
        PathOfTheTotemWarrior,
        PathOfWildMagic,
        PathOfTheZealot,
        // Bard
        CollegeOfCreation,
        CollegeOfEloquence,
        CollegeOfGlamour,
        CollegeOfLore,
        CollegeOfSpirits,
        CollegeOfSwords,
        CollegeOfValor,
        CollegeOfWhispers,
        // Cleric
        ArcanaDomain,
        DeathDomain,
        ForgeDomain,
        GraveDomain,
        KnowledgeDomain,
        LifeDomain,
        LightDomain,
        NatureDomain,
        OrderDomain,
        PeaceDomain,
        TempestDomain,
        TrickeryDomain,
        TwilightDomain,
        WarDomain,
        // Druid
        CircleOfDreams,
        CircleOftheLand,
        CircleOftheMoon,
        CircleOftheShepherd,
        CircleOfSpores,
        CircleOfStars,
        CircleOfWildfire,
        // Fighter
        ArcaneArcher,
        Banneret,
        BattleMaster,
        Cavalier,
        Champion,
        EchoKnight,
        EldritchKnight,
        PsiWarrior,
        RuneKnight,
        Samurai,
        // Paladin
        OathOfTheAncients,
        OathOfConquest,
        OathOfTheCrown,
        OathOfDevotion,
        OathOfGlory,
        OathOfRedemption,
        OathOfVengeance,
        OathOfTheWatchers,
        Oathbreaker,
        // Ranger
        BeastMasterConclave,
        FeyWanderer,
        GloomStalkerConclave,
        HorizonWalkerConclave,
        HunterConclave,
        MonsterSlayerConclave,
        Swarmkeeper,
        // Rogue
        ArcaneTrickster,
        Assassin,
        Inquisitive,
        Mastermind,
        Phantom,
        Scout,
        Soulknife,
        Swashbuckler,
        Thief,
        // Sorcerer
        AberrantMind,
        ClockworkSoul,
        DraconicBloodline,
        DivineSoul,
        ShadowMagic,
        StormSorcery,
        WildMagic,
        // Warlock
        Archfey,
        Celestial,
        Fathomless,
        Fiend,
        TheGenie,
        GreatOldOne,
        Hexblade,
        Undead,
        Undying,
        // Wizard
        SchoolOfAbjuration,
        SchoolOfBladesinging,
        SchoolOfChronurgy,
        SchoolOfConjuration,
        SchoolOfDivination,
        SchoolOfEnchantment,
        SchoolOfEvocation,
        SchoolOfGraviturgy,
        SchoolOfIllusion,
        SchoolOfNecromancy,
        OrderOfScribes,
        SchoolOfTransmutation,
        SchoolOfWarMagic,
    }
}