namespace DnD.Enums
{
    public enum Skill
    {
        //Strength
        Athletics,
        //Dexterity
        Acrobatics,
        SleightOfHand,
        Stealth,
        //Intelligence
        Arcana,
        History,
        Investigation,
        Nature,
        Religion,
        //Wisdom
        AnimalHandling,
        Insight,
        Medicine,
        Perception,
        Survival,
        //Charisma
        Deception,
        Intimidation,
        Performance,
        Persuasion,
    }
}